server:
  port: 8080

spring:
  application:
    name: nombremicro-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/nombremicro_db
      auto-index-creation: true



logging:
  level:
    pe.edu.vallegrande: DEBUG
