server:
  port: ${SERVER_PORT:9096}

spring:
  application:
    name: vg-ms-shopping

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      initial-size: 2
      max-size: 10
      max-idle-time: 3m
      max-life-time: 30m
      max-acquire-time: 10s
      validation-query: SELECT 1

  webflux:
    base-path: /

services:
  gateway-url: ${GATEWAY_URL:https://lab.vallegrande.edu.pe/sigrc/gateway}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: INFO
    pe.edu.vallegrande.sigrc.shopping: DEBUG
    org.springframework.r2dbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
